// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandError = { code: string, message: string, retryable: boolean,
/**
 * 乐观锁错误的服务端版本仅以字符串展示，不能经 JS number 往返。
 */
currentVersion: string | null, };

export type NotificationPermission = "granted" | "denied" | "notDetermined" | "unavailable";

export type NotificationPermissionView = { status: NotificationPermission, error: string | null, };

/**
 * 原生通知点击定位；旧会话事件不能把新账号 UI 聚焦到相同 UUID 的任务。
 */
export type ScrollTargetView = { notificationId: string, sessionGeneration: number, eventRevision: number, itemId: string, };

/**
 * 任务项（展示层只读投影）。
 */
export type ItemView = { id: string, text: string, done: boolean, createdAt: string, dueDate: string | null, updatedAt: string, };

/**
 * 一次变更后的完整快照（前端据此整体重渲染）。
 */
export type SnapshotView = { sessionGeneration: number, eventRevision: number, revision: number, items: Array<ItemView>, focusId: string | null, undoTitle: string | null, redoTitle: string | null, notifiedDueIds: Array<string>, saveFailed: boolean, };

/**
 * 同步状态可见视图。
 */
export type SyncStateName = "idle" | "pending" | "syncing" | "synced" | "failed" | "conflict" | "unauthorized";

export type SyncStatePayload = { sessionGeneration: number, eventRevision: number, state: SyncStateName, lastSyncAt: string | null, lastError: string | null, conflictCloudCount: number | null, conflictCloudVersion: string | null, conflictId: string | null, };

/**
 * 设置视图（与核心设置字段一一对应）。
 */
export type SettingsView = { revision: number, eventRevision: number, error: string | null, appearance: "system" | "light" | "dark", mode: "popover" | "panel", showFocusInMenuBar: boolean, menuBarTextLimit: number, notificationsEnabled: boolean, notificationSound: boolean, dueSoonEnabled: boolean, dueSoonHours: number, showOverdueInMenuBar: boolean, showOverdueBanner: boolean, automaticSync: boolean, };

/**
 * 登录状态（不发 Token，只发布尔与归属展示信息）。
 */
export type AuthStateView = { sessionGeneration: number, eventRevision: number, loggedIn: boolean, username: string | null, serverUrl: string | null, isAuthenticating: boolean, error: string | null, };

/**
 * 冲突面板展示的云端候选。
 */
export type ConflictView = { sessionGeneration: number, eventRevision: number, candidateId: string, reason: string, cloudVersion: string, cloudCount: number, cloudPreview: Array<ItemView>, updatedAt: string | null, };

export type MigrationStatus = { eventRevision: number, available: boolean, detectedFile: string | null, imported: boolean, error: string | null, backupPath: string | null, transactionId: string | null, recoveryRequired: boolean, preferencesAvailable: boolean, importedPreferences: boolean, requiresLogin: boolean, warnings: Array<string>, };

export type StartupView = { auth: AuthStateView, snapshot: SnapshotView, settings: SettingsView, sync: SyncStatePayload,
/**
 * 启动早期可能已进入冲突（订阅前的事件会丢）：随握手返回当前候选。
 */
conflict: ConflictView | null, legacyImportAvailable: boolean, migration: MigrationStatus | null, };

export type MutationView = {
/**
 * 此响应对应的已落盘修订，而不是稍后读取的内存修订。
 */
revision: number, message: string, offersUndo: boolean, id: string | null, };

export type TextArg = { text: string, };

export type DueArg = { due: string | null, };

export type MoveArg = { id: string, targetId: string, };

export type AuthArg = { username: string, password: string, };

export type CloudChoiceArg = { candidateId: string,
/**
 * 服务端 i64 保持十进制字符串跨 IPC，不能经过 JS number。
 */
cloudVersion: string, };

export type SettingsPatch = { appearance?: string, showFocusInMenuBar?: boolean, menuBarTextLimit?: number, notificationsEnabled?: boolean, notificationSound?: boolean, dueSoonEnabled?: boolean, dueSoonHours?: number, showOverdueInMenuBar?: boolean, showOverdueBanner?: boolean, automaticSync?: boolean, };

export type BoolArg = { enabled: boolean, };
