// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 任务项（展示层只读投影）。
 */
export type ItemView = { id: string, text: string, done: boolean, createdAt: string, dueDate: string | null, updatedAt: string, };

/**
 * 一次变更后的完整快照（前端据此整体重渲染）。
 */
export type SnapshotView = { revision: number, items: Array<ItemView>, focusId: string | null, undoTitle: string | null, redoTitle: string | null, notifiedDueIds: Array<string>, saveFailed: boolean, };

/**
 * 同步状态可见视图。
 */
export type SyncStateName = "idle" | "pending" | "syncing" | "synced" | "failed" | "conflict" | "unauthorized";

export type SyncStatePayload = { state: SyncStateName, lastSyncAt: string | null, lastError: string | null, conflictCloudCount: number | null, conflictCloudVersion: number | null, };

/**
 * 设置视图（与核心设置字段一一对应）。
 */
export type SettingsView = { appearance: "system" | "light" | "dark", mode: "popover" | "panel", showFocusInMenuBar: boolean, menuBarTextLimit: number, notificationsEnabled: boolean, notificationSound: boolean, dueSoonEnabled: boolean, dueSoonHours: number, showOverdueInMenuBar: boolean, showOverdueBanner: boolean, automaticSync: boolean, };

/**
 * 登录状态（不发 Token，只发布尔与归属展示信息）。
 */
export type AuthStateView = { loggedIn: boolean, username: string | null, serverUrl: string | null, isAuthenticating: boolean, };

/**
 * 冲突面板展示的云端候选。
 */
export type ConflictView = { cloudVersion: number, cloudCount: number, cloudPreview: Array<ItemView>, updatedAt: string | null, };

export type MigrationStatus = { available: boolean, detectedFile: string | null, imported: boolean, error: string | null, backupPath: string | null, };

export type StartupView = { auth: AuthStateView, snapshot: SnapshotView, settings: SettingsView, sync: SyncStatePayload, 
/**
 * 启动早期可能已进入冲突（订阅前的事件会丢）：随握手返回当前候选。
 */
conflict: ConflictView | null, legacyImportAvailable: boolean, migration: MigrationStatus | null, };

export type MutationView = { message: string, offersUndo: boolean, id: string | null, };

export type TextArg = { text: string, };

export type DueArg = { due: string | null, };

export type MoveArg = { id: string, targetId: string, };

export type AuthArg = { username: string, password: string, };

export type CloudChoiceArg = { 
/**
 * 用户确认时看到的云端候选版本（防“确认的不是当前展示快照”）。
 */
cloudVersion: number, };

export type SettingsPatch = { appearance?: string, showFocusInMenuBar?: boolean, menuBarTextLimit?: number, notificationsEnabled?: boolean, notificationSound?: boolean, dueSoonEnabled?: boolean, dueSoonHours?: number, showOverdueInMenuBar?: boolean, showOverdueBanner?: boolean, automaticSync?: boolean, };

export type BoolArg = { enabled: boolean, };
